language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t devnryn/docker-react -f Dockerfile.dev .
  
script:
    - docker run -e CI=true devnryn/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-200065275423"
    bucket_path: "docker-react"
    on:
        branch: master    
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"